.windows_job:
  tags:
    - saas-windows-medium-amd64
  before_script:
    - Set-Variable -Name "time" -Value (date -Format "%H:%m")
    - echo ${time}
  cache:
    paths:
      - ../perl
      - ../Compiler
    
build:
  extends:
    - .windows_job
  stage: build
  script:
    - 'if (Test-Path ..\perl) {Write-Host "perl is cached"} else { Invoke-WebRequest "https://github.com/StrawberryPerl/Perl-Dist-Strawberry/releases/download/SP_54001_64bit_UCRT/strawberry-perl-5.40.0.1-64bit-portable.zip" -OutFile ..\perl.zip ; Expand-Archive ..\perl.zip ..\perl }'
    - '$Env:PATH += ";$(Resolve-Path -Path ..\perl\c\bin);$(Resolve-Path -Path ..\perl\perl\bin);$(Resolve-Path -Path ..\perl\perl\site\bin)"'
    - 'cd "Project Files"'
    - "'NO_FASTDEP=1\r\nVERBOSE=1' | Out-File -FilePath Makefile.settings -Append"
    - '& "./Get Compiler.bat"'
    - 'perl compile.pl'
    - 'dir'
  artifacts:
    paths:
      - %CI_PROJECT_DIR%
    exclude:
      - "Project Files"
      - "Project Files/**/*"
      - ".git/**/*"
      - ".git"
