.windows_job:
  tags:
    - saas-windows-medium-amd64
  before_script:
    - Set-Variable -Name "time" -Value (date -Format "%H:%m")
    - echo ${time}
    - echo "started by ${GITLAB_USER_NAME} / @${GITLAB_USER_LOGIN}"

build:
  extends:
    - .windows_job
  stage: build
  script:
    - 'ls'
    - 'cd "Project Files"'
    - 'ls'
    - 'Invoke-WebRequest "https://github.com/StrawberryPerl/Perl-Dist-Strawberry/releases/download/SP_54001_64bit_UCRT/strawberry-perl-5.40.0.1-64bit.msi" -OutFile perl.msi'
    - 'msiexec /package perl.msi /quiet /passive'
    - '& "./Get Compiler.bat"'
    - 'perl compile.pl'
